version: '3.9'
services:
  opendyndns:
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - './data:/var/www/opendyndns/data'
      - './logs:/var/www/opendyndns/logs'
      - './web:/var/www/opendyndns/web'
    environment:
      - URL=http://localhost:8080
      - DOMAINS=example.com

    ports:
      - '53:53/udp'
      - '8080:80/tcp'
