version: '3.9'
services:
  opendyndns:
    image: 'hascheksolutions/opendyndns:latest'
    restart: unless-stopped

    volumes:
      - './data:/var/www/opendyndns/data'
      - './logs:/var/www/opendyndns/logs'
    environment:
      - URL=https://mydns.example.com
      - DOMAINS=example.com,sub.example.org
      - ALLOW_PRIVATE_IP=false
      - ALLOW_DYNAMIC_CREATION=false
      - NO_SECRET=false
    ports:
      - mode: host
        protocol: udp
        published: 53
        target: 53
      - mode: host
        protocol: tcp
        published: 8080
        target: 80
