version: '3.9'
services:
  opendyndns:
    build:
      context: .
      dockerfile: docker/Dockerfile

    volumes:
      - './data:/var/www/opendyndns/data'
      - './logs:/var/www/opendyndns/logs'
      - './web:/var/www/opendyndns/web'
    environment:
      - URL=http://localhost:8080
      - DOMAINS=example.com,orf.at

    ports:
      - mode: host
        protocol: udp
        published: 53
        target: 53
      - mode: host
        protocol: tcp
        published: 8080
        target: 80
